<?php namespace FormulaFantasy\Utilities;

include __DIR__ . '/Command.php';

use FormulaFantasy\TeamOwner\TeamOwner;

class calculatePointsCommand extends Command
{
    private $teamOwnerObject;
    private $completeArray;

    /**
     * calculatePointsCommand constructor.
     * @param TeamOwner $to
     * @param array $completeArray
     */
    public function __construct(TeamOwner $to, Array $completeArray)
    {
        $this->teamOwnerObject = $to;
        //$this->raceResults = $raceResults;
        $this->completeArray = $completeArray;
    }

    public function Execute()
    {
        //parent::Execute(); // TODO: Change the autogenerated stub
        //set points based on finish position
        //set points based on qualifying results
        //set points based on grid positions
        //set points based on qualifying buckets
        //set points based on penalties
        //set points based on fastest lap
        //set points based on constructor finish
        $this->teamOwnerObject->setPointsBasedOnDriver($this->completeArray);
        //$this->teamOwnerObject->setPointsBasedOnDriver($this->raceResults);
    }


}

