<?php

require_once __DIR__ . '/../../TestHelper.php';

use FormulaFantasy\Database\DatabasePlain;
use FormulaFantasy\Draft\Roster;
use PHPUnit\Framework\TestCase;

class RosterTest extends TestCase
{
    protected $db;

    public function test__construct()
    {

    }

    public function testAddDriver()
    {

    }

    public function testGetRoster()
    {

    }

    public function testGetRosterByOwner()
    {
        $rosObj = new Roster($this->db);
        $client = $rosObj->GetRosterByOwner(3, 1031);
        var_dump($client);
        $this->assertIsArray($client);
    }

    public function testSetRoster()
    {

    }

    /** @test  */
    public function Test_getConstructor()
    {
        $rosObj = new Roster($this->db);
        $client = $rosObj->getConstructor(832);
        $this->assertEquals(1, $client);
    }
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->db = new DatabasePlain();
    }
}
