<?php

require_once __DIR__ . '/../../TestHelper.php';

use FormulaFantasy\Database\DatabasePlain;
use PHPUnit\Framework\TestCase;
use FormulaFantasy\Score\PointValue;

class PointValueTest extends TestCase
{
    protected $db;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->db = new DatabasePlain();
    }

    /** @test  */
    public function Test_getPointsFromPlaceAndCategory()
    {
        $params = [1,'race'];
        $pObj = new PointValue($this->db);
        $result = $pObj->getPointsFromPlaceAndCategory($params);
        $this->assertEquals(25, $result);
    }

}