<?php namespace FormulaFantasy\Score;


class CalculateDriverPointsCommand extends ScoreCommand
{
    public function __construct()
    {
        parent::__construct();
    }

    public function Execute()
    {
        //get qualifying results line by driver

        //get best qualifying round

        //get net position change

        //get penalty code or status id-whever is best for seasaon

        //get fastest lap bool

        //parent::Execute(); // TODO: Change the autogenerated stub
    }

}