<?php namespace FormulaFantasy\Score;

require_once __DIR__ . '/ScoreCommand.php';

use FormulaFantasy\Database\DatabasePlain;
use FormulaFantasy\Driver\IDriver;
use FormulaFantasy\Results\QualifyingResultsDriver;
use FormulaFantasy\Results\RaceResultsDriver;

class CalculateManagerPointsCommand extends ScoreCommand
{
    public $ans;

    private $ScoreObject;
    //use draft or roster object in place here?
    private $rosterObject;
    private $completeArray;
    private $db;
    private $driverArray = [];

    public function RunScore(IDriver $driver)
    {
        //parent::RunScore(); // TODO: Change the autogenerated stub
        //points on driver race finish position

        //points on qualy finish position

        //points based on grid position minus finish position

        //points based on qualifying bucket

        //determine if penalties matter

        //points based on fastest lap

        //constructor points

    }

    /**
     * calculatePointsCommand constructor.
     * @param Score $so
     * @param array $completeArray
     */
    public function __construct(Roster $ro, Array $completeArray)
    {
        parent::__construct();
        $this->rosterObject = $ro;
        $this->completeArray = $completeArray;

        $this->driverArray = [
            'primaryDriverId' => $completeArray['primaryDriverId'],
            'secondaryDriverId' => $completeArray['secondaryDriverId'],
            'turboDriverId' => $completeArray['turboDriverId']
        ];
        $this->db = new DatabasePlain();
    }

    public function Execute()
    {
        $standardDriverRunningTotal = 0;
        $turboDriverRunningTotal = 0;

            //points on driver race finish position

            //points on qualy finish position

            //points based on grid position minus finish position

            //points based on qualifying bucket

            //determine if penalties matter

            //points based on fastest lap

            //constructor points


        $this->ans = $standardDriverRunningTotal;
    }
}