<?php namespace FormulaFantasy\Score;


class CalculateDriverPointsCommand extends ScoreCommand
{
    public function __construct()
    {
        parent::__construct();
    }

    public function Execute()
    {
        //parent::Execute(); // TODO: Change the autogenerated stub
    }

}