<?php namespace FormulaFantasy\Score;

include __DIR__ . '/ScoreCommand.php';

use FormulaFantasy\Score\Score;

class calculatePointsCommand extends ScoreCommand
{
    private $ScoreObject;
    private $completeArray;

    /**
     * calculatePointsCommand constructor.
     * @param Score $so
     * @param array $completeArray
     */
    public function __construct(Score $so, Array $completeArray)
    {
        $this->ScoreObject = $so;
        //$this->raceResults = $raceResults;
        $this->completeArray = $completeArray;
    }

    public function Execute()
    {
        //parent::Execute(); // TODO: Change the autogenerated stub
        //set points based on finish position
        //set points based on qualifying results
        //set points based on grid positions
        //set points based on qualifying buckets
        //set points based on penalties
        //set points based on fastest lap
        //set points based on constructor finish
        //$this->teamOwnerObject->setPointsBasedOnDriver($this->completeArray);
        $this->ScoreObject->calculatePointsForDriver($this->completeArray);
        //$this->teamOwnerObject->setPointsBasedOnDriver($this->raceResults);
    }


}

